routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ParentcompanyController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\StationController;
use App\Http\Controllers\LocationController;

Route::resource('parentcompanies', ParentcompanyController::class);
Route::resource('companies', CompanyController::class);
Route::resource('stations', StationController::class);

Route::get('near-places', [LocationController::class, 'index']);

Route::get('/', function () {
    return view('welcome');
});

app/Models/Station.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Station extends Model
{
  use HasFactory;
  protected $fillable = ['name', 'latitude', 'longitude', 'company_id', 'address'];

  static $rules = [
    'name' => 'required',
    'latitude' => 'required',
    'longitude' => 'required',
    'company_id' => 'required',
    'address' => 'required',
  ];

  protected $perPage = 20;
  public function company()
  {
    return $this->hasMany('App\Models\Company', 'id', 'company_id');
  }
  public function Parents()
  {
    return $this->hasMany('App\Models\Parentcompany', 'id', 'company_id');
  }
}

app/Http/Controllers/StationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Station;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class StationController extends Controller
{
    public function index()
    {
        $station = Station::latest()->paginate(5);

        return view('stations.index', compact('station'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        $station = DB::table('companies as c')
            ->leftjoin('parentcompanies as p', 'c.parent_company_id', '=', 'p.id')
            ->select('p.id', 'p.name', 'c.parent_company_id')
            ->distinct()
            ->whereNotNull('c.parent_company_id',)
            ->get();

        return view('stations.create', compact('station'));
    }
    public function store(Request $request)
    {
        request()->validate(Station::$rules);

        $station = Station::create($request->all());

        return redirect()->route('stations.index')
            ->with('success', 'Station created successfully.');
    }



    public function edit($id)
    {
        $station = Station::find($id);

        return view('stations.edit', compact('station'));
    }
    public function update(Request $request, Station $station)
    {
        request()->validate(Station::$rules);

        $station->update($request->all());

        return redirect()->route('stations.index')
            ->with('success', 'Station updated successfully');
    }
    public function destroy($id)
    {
        $station = Station::find($id)->delete();

        return redirect()->route('stations.index')
            ->with('success', 'Station deleted successfully');
    }
    public function show($id)
    {
        $station = Station::find($id);

        return view('stations.show', compact('station'));
    }
}
/*$latitude = "23.033863";
     $longitude = "72.585022";
     $users = User::select("name", \DB::raw("6371 * acos(cos(radians(" . $latitude . "))
             * cos(radians(latitude)) * cos(radians(longitude) - radians(" . $longitude . "))
             + sin(radians(" .$latitude. ")) * sin(radians(latitude))) AS distance"))
             ->having('distance', '<', 1000)
             ->orderBy('distance')
             ->get()->toArray();*/

resources/views/stations/create.blade.php
@extends('stations.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Station companies</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('stations.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Failed!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('stations.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Station Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Station Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Latitude:</strong>
                <input type="text" name="latitude" class="form-control" placeholder="Latitude Values">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Longitude:</strong>
                <input type="text" name="longitude" class="form-control" placeholder="Longitude">
            </div>
        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
            <strong>Company ID:</strong>
            <select name="company_id" id="company_id" class="form-control input-lg dynamic" data-dependent="city">
           
            @foreach ($station as $parent)
                       
                       <option value="{{$parent->name}}">{{$parent->name}}</option>
                       
                       @endforeach
         
            </select>
            </div>
        </div>



  
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Sation Address:</strong>
                <textarea class="form-control" style="height:150px" name="address" placeholder="Station Address"></textarea>
            </div>
            {{ csrf_field() }}
        </div>
     

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>



@endsection

resources/views/stations/edit.blade.php
@extends('stations.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Station </h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('stations.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Failed!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('stations.update',$station->id) }}" method="POST">
    @csrf
    @method('PUT')

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Station Name:</strong>
                <input type="text" name="name" value="{{ $station->name }}" class="form-control" placeholder="Station Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Latitude:</strong>
                <input type="text" name="latitude" value="{{ $station->latitude }}" class="form-control" placeholder="Latitude">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Longitude:</strong>
                <input type="text" name="longitude" value="{{ $station->longitude }}" class="form-control" placeholder="Longitude">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Station Name:</strong>
                <input type="text" name="company_id" value="{{ $station->company_id }}" class="form-control" placeholder="Compay ID" readonly>


            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Station Address:</strong>
                <input type="text" name="address" value="{{ $station->address }}" class="form-control" placeholder="Station address">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection

resources/views/stations/index.blade.php
@extends('stations.layout')
 
@section('content')
</br>
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h5>Station details</h5>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('stations.create') }}"> Create New station</a>
            </div>
        </div>
    </div></br>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Station Name</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Company ID</th>
            <th>Address</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($station as $pr_c)
       
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $pr_c->name }}</td>
            <td>{{ $pr_c->latitude }}</td>
            <td>{{ $pr_c->longitude }}</td>
            @if ($loop->iteration >=1)
            <td><b>{{ $pr_c->company_id}} </b></td>
            @endif
            <td>{{ $pr_c->address}}</td>
            <td>
                <form action="{{ route('stations.destroy',$pr_c->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('stations.show',$pr_c->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('stations.edit',$pr_c->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>

        @endforeach

        
    </table>
    {!! $station->links() !!}
@endsection

resources/views/stations/layout.blade.php
<!DOCTYPE html>
<html>
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Test</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Menu</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/stations">Station</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/parentcompanies">Parent Company</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/companies">Child Company</a>
        </li>
     
      </ul>
    </div>
  </div>
</nav>
<div class="container"></br>
<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>PHP Laravel framework Trial Work for Employeement </h2>
            </div>
            <div class="pull-right">
                
            </div>
        </div>
    </div>
    @yield('content')
    
</div>

</body>
</html>

resources/views/stations/show.blade.php
@extends('stations.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show station</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('stations.index') }}"> Back</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Station Name:</strong>
            {{ $station->name }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Latitude:</strong>
            {{ $station->latitude }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Longitude:</strong>
            {{ $station->longitude}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Company:</strong>
            {{ $station->company_id }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Address</strong>
            {{ $station->address}}
        </div>
    </div>
</div>
@endsection