routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ParentcompanyController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\StationController;
use App\Http\Controllers\LocationController;

Route::resource('parentcompanies', ParentcompanyController::class);
Route::resource('companies', CompanyController::class);
Route::resource('stations', StationController::class);

Route::get('near-places', [LocationController::class, 'index']);

Route::get('/', function () {
    return view('welcome');
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'parent_company_id',
    ];
    public function parentcompany()
    {
        return $this->hasOne('App\Models\Parentcompany', 'id', 'parent_company_id');
    }
    public function stations()
    {
        return $this->hasMany('App\Models\Station', 'company_id', 'id');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use Illuminate\Http\Request;
use App\Models\Parentcompany;

class CompanyController extends Controller
{
    public function index()
    {
        $company = Company::latest()->paginate(5);
        return view('companies.index', compact('company'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }


    public function create()
    {

        $companies = Parentcompany::all();
        return view('companies.create', compact('companies'));
    }
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'parent_company_id' => 'required',
        ]);

        Company::create($request->all());

        return redirect()->route('companies.index')
            ->with('success', 'Child company created successfully.');
    }

    public function show(Company $company)
    {
        return view('companies.show', compact('company'));
    }

    public function edit(Company $company)
    {
        if (request('eager')) {
            $companies = Parentcompany::with('companies')->get();
        } elseif (request('big')) {
            $companies = Parentcompany::with('companies')->has('companies', '>=', 3)->get();
        } else {
            $companies = Parentcompany::all();
        }
        return view('companies.edit', compact('company'));
    }
    public function update(Request $request, Company $company)
    {
        $request->validate([
            'name' => 'required',
            'parent_company_id' => 'required',
        ]);

        $company->update($request->all());

        return redirect()->route('companies.index')
            ->with('success', 'Child company updated successfully');
    }
    public function destroy(Company $company)
    {
        $company->delete();

        return redirect()->route('companies.index')
            ->with('success', 'Child company deleted successfully');
    }
}

resources/views/companies/create.blade.php
@extends('stations.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New child companies</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('companies.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Failed!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('companies.store') }}" method="POST">
    @csrf

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Company Name:</strong>

                <select require class="form-select" aria-label="Default select example" name="name" id ="name">
                    <option selected>Open this select menu</option>
                    
                  
                        @foreach ($companies as $parent)
                       
                        <option value="{{$parent->name}}">{{$parent->name}}</option>
                        
                        @endforeach
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Owned by Company:</strong>
                <select class="form-select" aria-label="Default select example" name="parent_company_id">
                    <option selected>Open this select menu</option>
                    
                  
                        @foreach ($companies as $pr_c)
                       
                        <option value="{{$pr_c->id}}">{{$pr_c->name}}</option>
                        
                        @endforeach
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection

resources/views/companies/edit.blade.php
@extends('stations.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit company </h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('companies.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Failed!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('companies.update',$company->id) }}" method="POST">
    @csrf
    @method('PUT')

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Child Company Name:</strong>
                <input type="text" name="name" value="{{ $company->name }}" class="form-control" placeholder="Child Company Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Parent Company:</strong>
                <select class="form-select" aria-label="Default select example" name="parent_company_id">
 

                    <option selected value="{{$company->parent_company_id}}">{{$company->parent_company_id}}</option>

                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection

resources/views/companies/index.blade.php
@extends('stations.layout')
 
@section('content')
</br>
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h5>Child Company details</h5>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('companies.create') }}"> Create New Parent Company</a>
            </div>
        </div>
    </div>
</br>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Company Name</th>
            <th>Parent Company ID</th>
            <th width="280px">Action</th>
        </tr>
  
            
        @foreach ($company as $pr_c)

        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $pr_c->name }}</td>
            <td><b>Code({{ $pr_c->parent_company_id }}): {{ $pr_c->parentcompany->name }} </b></td>
            <td>
                <form action="{{ route('companies.destroy',$pr_c->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('companies.show',$pr_c->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('companies.edit',$pr_c->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    
    </table>
  
    {!! $company->links() !!}
      
@endsection

resources/views/companies/show.blade.php
@extends('stations.layout')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show child Company</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('companies.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Child Company Name:</strong>
                {{ $company->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Parent Company Name:</strong>
                {{ $company->parent_company_id }}
            </div>
        </div>
    </div>
@endsection