routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ParentcompanyController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\StationController;
use App\Http\Controllers\LocationController;

Route::resource('parentcompanies', ParentcompanyController::class);
Route::resource('companies', CompanyController::class);
Route::resource('stations', StationController::class);

Route::get('near-places', [LocationController::class, 'index']);

Route::get('/', function () {
    return view('welcome');
});

app/Models/Parentcompany.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Parentcompany extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'address',
    ];
    public function companies()
    {
        return $this->hasMany('App\Models\Company', 'parent_company_id', 'id');
    }
}

app/Http/Controllers/ParentcompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Parentcompany;
use Illuminate\Http\Request;

class ParentcompanyController extends Controller
{
    public function index()
    {
        if (request('eager')) {
            $companies = Parentcompany::with('companies')->get();
        } elseif (request('big')) {
            $companies = Parentcompany::with('companies')->has('companies', '>=', 3)->get();
        } else {
            $companies = Parentcompany::all();
        }
        return view('parentcompanies.index', compact('companies'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        $companies = Parentcompany::all();
        return view('parentcompanies.create', compact('companies'));
    }
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'address' => 'required',
        ]);

        Parentcompany::create($request->all());

        return redirect()->route('parentcompanies.index')
            ->with('success', 'Parent company created successfully.');
    }

    public function show(Parentcompany $parentcompany)
    {
        return view('parentcompanies.show', compact('parentcompany'));
    }

    public function edit(Parentcompany $parentcompany)
    {
        return view('parentcompanies.edit', compact('parentcompany'));
    }
    public function update(Request $request, Parentcompany $parentcompany)
    {
        $request->validate([
            'name' => 'required',
            'address' => 'required',
        ]);

        $parentcompany->update($request->all());

        return redirect()->route('parentcompanies.index')
            ->with('success', 'parent company updated successfully');
    }
    public function destroy(Parentcompany $parentcompany)
    {
        $parentcompany->delete();

        return redirect()->route('parentcompanies.index')
            ->with('success', 'Parent company deleted successfully');
    }
}

resources/views/parentcompanies/create.blade.php
@extends('stations.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New parent companies</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('parentcompanies.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Failed!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('parentcompanies.store') }}" method="POST">
    @csrf

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Company Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Company Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Address:</strong>
                <textarea class="form-control" style="height:150px" name="address" placeholder="Address detail"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>


</form>
@endsection

resources/views/parentcompanies/edit.blade.php
@extends('stations.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit company </h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('parentcompanies.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Failed!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('parentcompanies.update',$parentcompany->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Company Name:</strong>
                    <input type="text" name="name" value="{{ $parentcompany->name }}" class="form-control" placeholder="Company Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Address Detail:</strong>
                    <textarea class="form-control" style="height:150px" name="address" placeholder="Address Detail">{{$parentcompany->address}}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/parentcompanies/index.blade.php
@extends('stations.layout')
 
@section('content')
</br>
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h5>Parent Company details</h5>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('parentcompanies.create') }}"> Create New Parent Company</a>
            </div>
        </div>
    </div>
</br>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th> Parent Companies</th>
            <th >Parent Addresses</th>
            <th>Number of Child companies</th>
            <th> List of Child companies</th>
            <th width="280px" >Action</th>
        </tr>
    
        @foreach ($companies as $pr_c)
            @foreach ($pr_c->companies as $child)
        <tr>
            
            @if ($loop->iteration ==1)
            <td>{{ ++$i }}</td>
            <td >{{$pr_c->name }}</td>
            @endif
            @if ($loop->iteration > 1)
            <td></td>
            @endif
            @if ($loop->iteration ==1)
            <td rowspan = "{{ $pr_c->companies->count() }}">{{$pr_c->address}}</td>
            @endif
          
            @if ($loop->iteration > 1)
            <td></td>
            @endif
            <td > @if ($loop->iteration == 1)
                <b>{{ $pr_c->name }}: {{ $pr_c->companies->count() }} company/ies</b>
                @endif
            </td>
            <td>{{ $child->name }}</td>
            <td>
                <form action="{{ route('parentcompanies.destroy',$pr_c->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('parentcompanies.show',$pr_c->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('parentcompanies.edit',$pr_c->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
        @endforeach
    </table>
  
 
      
@endsection

resources/views/parentcompanies/show.blade.php
@extends('stations.layout')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Parent Company</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('parentcompanies.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $parentcompany->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Adress Details:</strong>
                {{ $parentcompany->address }}
            </div>
        </div>
    </div>
@endsection